services:
  react:
    image: node:19-alpine
    command: sh -c "npm install && npm run start"
    working_dir: /frontend
    ports:
      - 3000:3000
    volumes: 
      - ./frontend/:/frontend

  express:
    image: node:19-alpine
    command: sh -c "npm install && npm run start"
    working_dir: /express
    ports:
      - 3001:3001
    volumes: 
      - ./backend/:/express

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 8080:8080
